name: Deploy Terraform

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-terraform.yaml
      - terraform/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-central-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Terraform Init
        run: |
          terraform -chdir=terraform/environments/aws init

      - name: Terraform Apply
        run: |
          terraform -chdir=terraform/environments/aws apply -auto-approve -input=false
