name: Deploy Terraform (and Backend)

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-terraform.yaml
      - terraform/**
      - backend/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Init
        run: |
          terraform -chdir=terraform/environments/aws init

      - name: Terraform Apply
        run: |
          terraform -chdir=terraform/environments/aws apply -auto-approve -input=false
